const config = {
  address: 'XRUHBDGYBYQO9IXXTPTJWKQOCMKLOFUTTARNS9DJN99SAQMFKVKFFFJWCCVZS9DWQYGZNFFBCEKKFPAGD',
  seed: 'BGBLSNZFLKNXZRCXERDNSRBHMSUULSDTRPTSVPX9XOQXZZYHIIGZREGLS9VCKTKP9VBDYFZQGLHPNEKKZ',
};

export default config;
